### ISSUE TITLE
Fabric 1.20.2 - Mod causes Fabric server to crash when starting up.

### ISSUE THREAD

**Issue by ghost** [Nyphet/nightworld#1]
Installed this mod to a existing world and whenever I start it up, it will cause the server to crash due to "server tick loop". I have already tried doing the common fix to server tick loop crash, which is deleting json files, but however the mod still causes the server to crash. I am using to Bisect to host with 5 GB RAM, if this detail matters.

**Comment by Crystal-Spider** [comment]
Some quick questions:

1. If the world was working fine before, is this the only mod you recently added?
2. Is there any other mod on the server? If so, could you provide a list?

Thank you

**Comment by Crystal-Spider** [comment]
Quick update:  
I created my own server (hosted on my machine) with only Nightworld installed, and it runs without issues.  
Also, I know of a private server that runs on Fabrci 1.20.1 (but shouldn't change much from 1.20.2) that has Nightworld installed with some other server-side only mods, and it runs fine.

I think I'm going to need more information about your setup because I can't seem to replicate the issue.

**Comment by No1129** [comment]
its lithium i think

**Comment by ghost** [comment]
Hello, sorry for late reply. I have fixed the issue and it was caused by Lithium as suggested by No1129.  Thank you.
